### ISSUE TITLE
scReadCount: -G option

### ISSUE THREAD

**Issue by vbruat** [HorvathLab/NGS#1]
Hi,

I'm trying to use scReadCount but the barcode of the cell in my bam is in the CB tag. I don't know how to specify this in the advanced -G option.
Example:
A00469:88:HNL2KDMXX:2:1209:31476:14231  16      1       14658   255     98M     *       0       0       CAAGTCTGGGTCTGGGGGGGAAGGTGTCATGGAGCCCCCTACGATTCCCAGTCGTCCTCGTCCTCCTCTGCCTGTGGCTGCTGCGGTGGCGGCAGAGG -FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF      **CB:Z:GCTGCGAAGATCTGCT-1** UB:Z:ACATTGACTT RE:A:I  PG:Z:MarkDuplicates     RG:Z:CPTP_0012:0:1:HNL2KDMXX
:2 NH:i:1       HI:i:1  nM:i:0  CR:Z:GCTGCGAAGATCTGCT   UR:Z:ACATTGACTT AS:i:96 CY:Z:FFFFFFFFF:FFFFFF   UY:Z::FFFFFFFFF xf:i:0  li:i:0

Thanks.

**Comment by edwardsnj** [comment]
The provide options for the cell-barcode  (aka read grouping) are: STARsolo and UMI-tools. Turns out, the STARsolo grouping is what you need. Its definition (in the group.ini file) is:

    [STARsolo]
    Description: Cell barcodes added by STARsolo in CB tag in aligned read, reads without a CB tag dropped.
    ReadTagValue: tag='CB'

If you'd like to provide a value for reads without a CB tag (instead of dropping them) or use your own name for the grouping strategy:

    [MyBarcodes]
    Description: Cell barcodes from my BAM file.
    ReadTagValue: tag='CB' missing='CBMISSING'

in a file group.ini in the working directory where you run SCReadCounts (you can change group.ini in the distribution, but you might overwrite it with a new release). 
 
Specify: -G STARsolo or -G MyBarcodes

Let me know if this doesn't do what you need!

Cheers!

- n

**Comment by vbruat** [comment]
Hi,
Thanks for answering me quickly, I've tried the option -G STARsolo but I get the following error:

Traceback (most recent call last):
  File "scReadCounts.py", line 169, in <module>
NameError: name 'readgropup' is not defined
[6655] Failed to execute script scReadCounts

**Comment by edwardsnj** [comment]
Sorry about that. You must be on release 1.1.3 or earlier, that was fixed in release 1.1.4. You should find this problem goes away with the most recent release.

**Comment by vbruat** [comment]
You're right, I changed to version 1.1.4 and it works!

Thank you!!!
