### ISSUE TITLE
scVarLoci from cellranger 7.10

### ISSUE THREAD

**Issue by gabrielascui** [HorvathLab/NGS#16]
Hi ! I have been trying to run `scVarLoci` on the `possorted_genome_bam.bam` generated from cellranger. 

I'm getting the following error message: 

`Traceback (most recent call last):
  File "/mnt/BioHome/gascui/local/SCReadCounts-1.3.2.Python-3.7/bin/../src/scVarLoci.py", line 36, in <module>
    cellbarcodes,umis = sys.argv[2].split(':')
ValueError: not enough values to unpack (expected 2, got 1)`

If I use the bam file on the data directory, I get the same error. 

If I replace sys.argv[2] to be "5:5", I get this error:

`Traceback (most recent call last):
  File "/mnt/BioHome/gascui/local/SCReadCounts-1.3.2.Python-3.7/bin/../src/scVarLoci.py", line 37, in <module>
    assert cellbarcodes in groupMap
AssertionError`

This is my script: 

`
OUTFILE="${SOURCEDIR}/output/scReadCounts/sc_snv_loci_test.txt"
BAMFILE="~/local/SCReadCounts-1.3.2.Python-3.7/data/singlecell2_117.bam"
MINVARREADCOUNT="10"
REGION="chr7"

scVarLoci $BAMFILE $MINVARREADCOUNT $REGION > $OUTFILE

`

Thank you in advance!

Gabriel

**Comment by edwardsnj** [comment]
`scVarLoci` isn't described in the documentation, but a program called `varLoci` is [documented](https://horvathlab.github.io/NGS/SCReadCounts/docs/Discovery.html). `varLoci` has the command-line arguments you used with `scVarLoci`.

The two programs are not the same, and at this time, I consider only `varLoci` supported. 

Nevertheless, here is the command-line for `scVarLoci`:
```
% scVarLoci <bam_file>.bam <CellBarcodeStrategy>:<UMIStrategy> [ <min_cells_w_var>:<min_umi_w_var> [ <region> ] ]
```
Same caveats for the `.bam` file as for `varLoci`. Default value for `<min_cells_w_var>` is 2, for `<min_umi_w_var>` is 3. 

The `<CellBarcodeStrategy>` should be the name of a strategy from the distributed groups.ini file (or your own) that defines how cell barcodes should be extracted from the read metadata - you probably want `CellRanger_CB`. Similarly for `<UMIStrategy>` - you probably want `CellRanger_UMI`. 

You can find documentation of the methods for specifying these strategies in the documentation on [Read Grouping](https://horvathlab.github.io/NGS/SCReadCounts/docs/Grouping.html), and the distributed strategies in the file [group.ini](https://github.com/HorvathLab/NGS/blob/master/common/src/group.ini). Note that the `CellRanger_CB` expects to find a file `barcodes.tsv` of acceptable barcodes and no command-line option is provided to override this. You can create your own Read Group file to work around this if you need, or just modify the distributed groups.ini file. 

There are additional hardcoded parameters in the scVarLoci script which may or may not be relevant to your usecase. You can see these for yourself since you appear to be using the source code distribution.

Hope this helps...

**Comment by edwardsnj** [comment]
Oops, my bad, checked the source code. I'm handling the distinction between cell barcode and umi extraction strategies for the user so "CellRanger:CellRanger" will do the trick. barcodes.tsv should be in your current working directory (where you are running the command from).

**Comment by gabrielascui** [comment]
Thank you it's working now !

**Comment by gabrielascui** [comment]
Sorry, I was able to run the example bam file, but when I try to use my own I don't get an stdout from `scVarLoci`.  ¯\_(ツ)_/¯ 

this is what the lines in my bam file look like if i do a quick `samtools view`:

`A00475:649:HLJ2TDMXY:1:2105:26205:22169	16	chr1	3016274	0	90M	*	0	0	CCCATATCTTCGAGGCTTTTCCCTACTTTCTCCTCTGTAAGTTTCAGTGTCTCTGGTTTTATGTGGAGTTCCTTAATCCACTTAGATTTG	ABEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE	NH:i:9	HI:i:1	AS:i:88	nM:i:0	RG:Z:counts_wade_crispr:0:1:HLJ2TDMXY:1	RE:A:I	xf:i:0	CR:Z:TCCTCTTTCGTCACCT	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:TCCTCTTTCGTCACCT-1	UR:Z:TGGTTCCTATAA	UY:Z:FFFFFFFFFFFF	UB:Z:TGGTTCCTATAA	ZQ:Z:EDA@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@A	NM:i:0	MD:Z:90`

This is from the example bam file:

`SRR10018152.98817699	272	1	14470	0	98M	*	0	0	GCAGGCTGGGTGGAGCCGTCCCCCCATGGAGCACAGGCAGACAGAAGTCCCCGCCCCAGCTGTGTGGCCTCAAGCCAGCCTTCCGCTCCTTGAAGCTG	JJJJJJJJJJJJJJJJJFAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJFFFAA	NH:i:7	HI:i:5	AS:i:96	nM:i:0	NM:i:0	MD:Z:98	CR:Z:CACCTTGCGTCCGCGA	UR:Z:GTAGTCAAAC	sS:Z:CACCTTGCGTCCGCGAGTAGTCAAAC	sQ:Z:AAFFFJJJFJFJJJJJJJJJJJJJJJ	sM:i:1	CB:Z:CACCTTGCATCCGCGA	UB:Z:GTAGTCAAAC`

Seems to me that the tags are in different positions for some reason... I'm not an expert in using bam files tbh, any guidance would be welcome.

Best,

Gabriel

**Comment by edwardsnj** [comment]
Hmmm. Not sure what is going on - it looks like the necessary tags are present. Order of tags is not important. You could try varLoci (ignores cell-barcodes) with a min-readcount of, say, 3 to generate loci with any evidence of variation and then try a few of them with readCounts / scReadCounts to see what they look like as cell-specific variants. The quality scores for your real data (F) look less good than the quality scores for your example file (J), but the quality threshold is 35, for which F is just fine. Why do you believe there are variants to find? Did you align in a way that permitted alignments with mismatches? 

Is there any way you can share a portion of your BAM file with me to help you diagnose the issue?

**Comment by edwardsnj** [comment]
Quick thought - did you update the barcodes file? CellRanger barcodes have a -1 on the end of them, too.

**Comment by gabrielascui** [comment]
> Hmmm. Not sure what is going on - it looks like the necessary tags are present. Order of tags is not important. You could try varLoci (ignores cell-barcodes) with a min-readcount of, say, 3 to generate loci with any evidence of variation and then try a few of them with readCounts / scReadCounts to see what they look like as cell-specific variants. The quality scores for your real data (F) look less good than the quality scores for your example file (J), but the quality threshold is 35, for which F is just fine. Why do you believe there are variants to find? Did you align in a way that permitted alignments with mismatches?

Using varLoci worked! I now got the variants with scReadCounts as well. 

Thank you !

The quality was for some reason altered once I added the MD tags with `samtools`, the original BAM file has a similar quality (mostly F). 

Thank you again!
