### ISSUE TITLE
scReadCounts - Filter parameters?

### ISSUE THREAD

**Issue by Romeo1-1** [HorvathLab/NGS#7]
Hello, thank you for this package! I've been able to use your package on both scDNA & scRNAseq and it was very handy.

I have a question regarding the "alignement filter". I'm studying scRNA seq analyses of 2 samples of cancer cells from a patient, before and after treatment. I want to study a particular SNV but I cannot detect it using scReadCounts (I only detect the reference allele). I know from other experiment that this mutation has a very small allelic fraction (should be around 1-2%), but interestingly, I've been able to identify it with IGV and samtools view on this particular sample. With scReadCounts I was hoping  to know which cells have the mutations.

In general, I noticed that I have fewer total reads in scReadCounts output compared to IGV and samtools view. This may be due to the "alignement filter". Is there any way to adjust it? Do you have any other idea about the origin of this problem?

Thank you a lot in advance,

**Comment by Romeo1-1** [comment]
Hello,

After looking more closely to the files, I was able to create my own filter in filter.ini, using these parameters:

```
BasicFilter:          skip_duplicate=False
                      skip_secondary=False
                      skip_qcfail=False
                      skip_unmapped=False
```

But it didn't change anything, meaning that I get the same exact output when using Basic or my custom filter. Is this normal? 

Thank you a lot in advance,

**Comment by edwardsnj** [comment]
Hi Remi, thanks for the nice feedback. It is not impossible, but I think it is unlikely to be a filtering issue. The BasicFilter is very basic - it is essentially just eliminating alignments where the allele at the locus cannot be reliably determined. You might find the documentation on filtering useful, see: 

https://github.com/HorvathLab/NGS/blob/master/SCReadCounts/docs/Filtering.md

Nevertheless, this doesn't help you with the locus you are interested in. It is possible that the cells with the variant are not in the filtered list of STARsolo barcodes (if you are using them). It is also possible it is just going missing due to inconsistencies in how the contigs/chromosomes are labeled, although this seems unlikely since you are able to count the reference allele. Lastly, IGV/samtools view will show you everything, even secondary alignments. Perhaps the variants you see in IGV are from misplaced or other problematic alignments. 

Its hard to guess what the issue is, let me know if you can share the alignments from the region of interest and the locus, so I can attempt to figure out the issue. 

I'm also happy to suggest additional debugging strategies. 

It also might help if you could provide the command-line you are using (or as is printed in the output). 

Edge cases (which I'm guess this one is) can be subtle to figure out, but there is usually a good reason. Once we figure out what is going on, you can decide whether you still believe the variant is present! :-)

- n

**Comment by Romeo1-1** [comment]
Hello @edwardsnj 

That was the commandline I used
`readCounts -s "mutations.csv" -r "possorted_bam.bam" -f "NoF" -m 0 -B 10000 -G "CellRanger_CB" -b "barcodes.tsv" -o "scReadCounts/Test.csv"`

Since these are patients sample, I cannot send you my data, I'm sorry. I think you're right, it's probably not the filter or labeling inconsistencies but it could be secondary alignments. After looking closer, the QF score in IGV for these reads is very low (less than 20 most of the time), and when using VarTrix I end up with the same results as scReadCounts. So I don't think this variant is truly present.

Thank you for your quick answer and your help !

**Comment by edwardsnj** [comment]
Oh, one final thought, since it looks like you are using the readCounts program directly (it does most of the work anyway). readCounts has an extended output option that provides counts of the reads at each locus that are rejected by one of the filters. 

 --extended "Read filtering statistics"

Cheers!
